# Generated by Django 4.2.27 on 2026-05-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='キー')),
                ('label', models.CharField(max_length=100, verbose_name='表示名')),
                ('block_type', models.CharField(choices=[('text', 'text'), ('list', 'list'), ('steps', 'steps'), ('faq', 'faq'), ('links', 'links'), ('contact', 'contact')], max_length=20, verbose_name='ブロック種別')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': 'ブロック定義',
                'verbose_name_plural': 'ブロック定義',
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部署名')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タグ名')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('tag_type', models.CharField(choices=[('tool', 'tool'), ('situation', 'situation'), ('business', 'business'), ('audience', 'audience')], max_length=20, verbose_name='タグ種別')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='対象者名')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '対象者',
                'verbose_name_plural': '対象者',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('page_type', models.CharField(choices=[('application', '申請方法'), ('trouble', 'トラブル対応'), ('rule', '社内ルール')], max_length=20, verbose_name='ページタイプ')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '公開中'), ('private', '非公開'), ('needs_update', '要更新')], default='draft', max_length=20, verbose_name='公開状態')),
                ('urgency', models.CharField(choices=[('normal', '通常'), ('high', '急ぎ'), ('urgent', '緊急')], default='normal', max_length=20, verbose_name='緊急度')),
                ('summary', models.TextField(blank=True, verbose_name='概要')),
                ('primary_action', models.TextField(blank=True, verbose_name='まずやること')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='knotly.category', verbose_name='カテゴリ')),
                ('owner_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_pages', to='knotly.department', verbose_name='担当部署')),
                ('tags', models.ManyToManyField(blank=True, related_name='pages', to='knotly.tag', verbose_name='タグ')),
                ('target_audiences', models.ManyToManyField(blank=True, related_name='pages', to='knotly.targetaudience', verbose_name='対象者')),
            ],
            options={
                'verbose_name': 'ページ',
                'verbose_name_plural': 'ページ',
                'ordering': ('-updated_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('title', models.CharField(max_length=100, verbose_name='見出し')),
                ('content', models.JSONField(default=dict, verbose_name='内容')),
                ('is_required', models.BooleanField(default=False, verbose_name='必須')),
                ('is_visible', models.BooleanField(default=True, verbose_name='表示')),
                ('block_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='knotly.blockdefinition', verbose_name='ブロック定義')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='knotly.page', verbose_name='ページ')),
            ],
            options={
                'verbose_name': 'ブロック',
                'verbose_name_plural': 'ブロック',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('page', 'block_definition'), name='unique_block_definition_per_page'),
        ),
    ]
