# Generated by Django 4.2.27 on 2026-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knotly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('application', '申請方法'), ('trouble', 'トラブル対応'), ('rule', '社内ルール'), ('custom', '自由作成')], max_length=20, verbose_name='ページタイプ'),
        ),
    ]
